name: SweetFlight
version: '${version}'
main: top.mrxiaom.sweet.flight.SweetFlight
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - Residence
authors: [ MrXiaoM ]
folia-supported: true
libraries:
  - "org.jetbrains:annotations:24.0.0"
commands:
  sweetflight:
    description: 'The main command of SweetFlight'
    aliases: [ sweetfly, sflight, sfly, sf ]
